image: gradle:7.4.2-jdk17

stages:
  - checkstyle
  - test
  - build
  - deploy


unit_test:
  stage: test
  script:
    - gradle test

checkstyle:
  stage: checkstyle
  script:
    - gradle check
  allow_failure: true

docker_build:
  stage: build
  script:
    - echo "create docker container"

deploy_to_prod:
  stage: deploy
  script:
    - echo "deploy docker container"
